# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  #config.vm.box = "puppetlabs/centos-7.0-64-puppet"
  config.vm.box = "puppetlabs/centos-6.6-64-nocm"
  config.vm.hostname = "mars"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "bootstrap", type: "shell", inline: <<-SHELL
     rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-pc1-el-6.noarch.rpm
     yum install -y puppet
     yum install -y git
     git clone https://juaningan:20bfa4250edeb51f53834ecd7d9456661cac3441@github.com/juaningan/vdc-mars-bootstrap
     export FACTER_PUPADIR=$(echo $PWD/vdc-mars-bootstrap)
     /opt/puppetlabs/puppet/bin/puppet apply ${FACTER_PUPADIR}/manifests/puppet.pp
     /opt/puppetlabs/puppet/bin/puppet apply ${FACTER_PUPADIR}/manifests/r10k.pp
  SHELL

  config.vm.provision "puppet-apply", type: "shell", inline: <<-SHELL
     /opt/puppetlabs/puppet/bin/r10k deploy environment -pv
     ln -s /vagrant/$HOSTNAME.yaml /etc/puppetlabs/code/environments/development/hieradata/nodes/$HOSTNAME.yaml
     /opt/puppetlabs/puppet/bin/puppet apply /etc/puppetlabs/code/environments/development/manifests/site.pp --environment=development
  SHELL

  config.vm.provision "extra", type: "shell", inline: <<-SHELL
     cd /var/www/html
     rm -rf *.git
     git clone --mirror https://juaningan:20bfa4250edeb51f53834ecd7d9456661cac3441@github.com/Telefonica/vdc-puppet-bootstrap
     cd vdc-puppet-bootstrap.git; git update-server-info; cd - 
     git clone --mirror https://juaningan:20bfa4250edeb51f53834ecd7d9456661cac3441@github.com/Telefonica/vdc-r10k-controlrepo
     cd vdc-r10k-controlrepo.git; git update-server-info; cd - 
     git clone --mirror https://github.com/puppetlabs/puppetlabs-stdlib
     cd puppetlabs-stdlib.git; git update-server-info; cd - 
     git clone --mirror https://github.com/puppetlabs/puppetlabs-concat
     cd puppetlabs-concat.git; git update-server-info; cd - 
     git clone --mirror https://github.com/nanliu/puppet-staging
     cd puppet-staging.git; git update-server-info; cd - 
     git clone --mirror https://github.com/puppetlabs/puppetlabs-ibm_installation_manager
     cd puppetlabs-ibm_installation_manager.git; git update-server-info; cd - 
     git clone --mirror https://github.com/puppetlabs/puppetlabs-firewall
     cd puppetlabs-firewall.git; git update-server-info; cd - 
     git clone --mirror https://github.com/hunner/puppet-wordpress
     cd puppet-wordpress.git; git update-server-info; cd - 
     git clone --mirror https://github.com/puppetlabs/puppetlabs-mysql
     cd puppetlabs-mysql.git; git update-server-info; cd - 
     git clone --mirror https://github.com/puppetlabs/puppetlabs-apache
     cd puppetlabs-apache.git; git update-server-info; cd - 
     git clone --mirror https://github.com/puppetlabs/puppetlabs-tomcat
     cd puppetlabs-tomcat.git; git update-server-info; cd - 
     git clone --mirror https://github.com/puppetlabs/puppetlabs-websphere
     cd puppetlabs-websphere.git; git update-server-info; cd - 
  SHELL

end
